import 'package:flutter/material.dart';
import '../../../../core/crypto/account_encryption_service.dart';
import '../../../../core/crypto/master_key_service.dart';
import '../../../../core/device/device_id_service.dart';
import '../../../../core/di/injector.dart';
import '../../../../core/theme/widget_styles.dart';
import '../../../../core/widgets/adaptive_progress_indicator.dart';
import '../../../auth/data/auth_repository.dart';
import 'recovery_code_screen.dart';

/// Adds a recovery code to an account that has none (contract §C.1.1).
///
/// One screen for both cases, because they are the same case. A brand-new
/// account gets its master key wrapped under the password alone
/// (`MasterKeyService.establish`), and every account created before §C.1.1 is in
/// exactly that state already - so "first-time setup" and "retrofit" differ only
/// in how long the account has been sitting one password reset away from losing
/// every backup blob and its account identity key.
///
/// **Ordering is the whole design.** The code is generated, shown, and confirmed
/// by re-entry *before* anything is written. Committing first and showing
/// afterwards is the obvious shape and it is wrong: the wrapping would exist, the
/// account would report `ready`, the prompt would never fire again, and a user
/// who backed out of the confirmation screen would hold no copy of the only
/// credential that survives a password reset. Confirm-then-commit makes backing
/// out free - nothing changed, and the next launch asks again.
///
/// The password is collected here rather than assumed. `PUT backup/recovery-key`
/// is gated on it server-side (§C.1's "requires re-authentication"), and a cold
/// start has none, so a flow that could only run at sign-in would reach almost
/// nobody.
class RecoveryCodeSetupScreen extends StatefulWidget {
  const RecoveryCodeSetupScreen({super.key});

  @override
  State<RecoveryCodeSetupScreen> createState() =>
      _RecoveryCodeSetupScreenState();
}

class _RecoveryCodeSetupScreenState extends State<RecoveryCodeSetupScreen> {
  final _password = TextEditingController();
  bool _busy = false;
  String? _error;

  /// Held across a failed commit so a mistyped password does not cost the user
  /// the code they just wrote down.
  String? _generated;

  @override
  void dispose() {
    _password.dispose();
    super.dispose();
  }

  Future<void> _start() async {
    final password = _password.text;
    if (password.isEmpty) {
      setState(() => _error = 'Enter your account password to continue.');
      return;
    }

    final userId = getIt<AuthRepository>().currentUserId;
    final deviceId = getIt<DeviceIdService>().deviceIdOrNull;
    if (userId == null || deviceId == null) {
      setState(() => _error = 'You are not signed in.');
      return;
    }

    setState(() {
      _busy = true;
      _error = null;
    });

    final masterKeys = getIt<MasterKeyService>();

    try {
      // Generated by the engine, never in Dart: the alphabet and the rejection
      // sampling are wire format shared with the desktop client (§C.1.2), and a
      // second implementation of them is how they diverged the first time.
      final code = _generated ??= await masterKeys.generateRecoveryCode();

      if (!mounted) return;
      final confirmed = await Navigator.of(context).push<bool>(
        MaterialPageRoute(
          fullscreenDialog: true,
          builder: (_) => RecoveryCodeScreen(recoveryCode: code),
        ),
      );
      if (confirmed != true) {
        // Nothing was written. Deliberate - see the class comment.
        if (mounted) setState(() => _busy = false);
        return;
      }

      final stored = await masterKeys.addRecoveryCode(
        userId: userId,
        deviceId: deviceId,
        password: password,
        recoveryCode: code,
      );
      if (stored == null) {
        setState(() {
          _busy = false;
          _error =
              'Your master key is not unlocked on this device yet. Sign out '
              'and back in, then try again.';
        });
        return;
      }

      await getIt<AccountEncryptionService>().markRecoveryCodeSaved(userId);
      if (mounted) Navigator.of(context).pop(true);
    } on RecoveryCodeNotStoredException {
      // A 200 that stored nothing. Surfaced rather than swallowed: telling
      // someone they are protected when they are not is worse than not offering
      // the retrofit at all.
      setState(() {
        _busy = false;
        _error =
            'The server accepted the code but did not store it, so it would '
            'not open anything. Nothing has changed - please try again later.';
      });
    } catch (e) {
      setState(() {
        _busy = false;
        _error = _describe(e);
      });
    }
  }

  static String _describe(Object error) {
    final text = error.toString();
    if (text.contains('password')) {
      return 'That password was not accepted. Nothing has changed.';
    }
    return 'Could not save a recovery code right now. Nothing has changed.';
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(title: const Text('Recovery code')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSpacing.m),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Protect your encrypted messages',
                style: theme.textTheme.titleMedium,
              ),
              const SizedBox(height: AppSpacing.s),
              Text(
                'Right now, resetting your password would make your encrypted '
                'message history permanently unreadable — including on this '
                'phone. A recovery code is the only thing that survives a '
                'reset. It takes a minute and you only do it once.',
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onSurface.withValues(alpha: 0.75),
                ),
              ),
              const SizedBox(height: AppSpacing.l),
              TextField(
                controller: _password,
                obscureText: true,
                autocorrect: false,
                enableSuggestions: false,
                enabled: !_busy,
                decoration: InputDecoration(
                  labelText: 'Account password',
                  errorText: _error,
                  border: const OutlineInputBorder(),
                ),
                onSubmitted: (_) => _busy ? null : _start(),
              ),
              const SizedBox(height: AppSpacing.l),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: _busy ? null : _start,
                  child: _busy
                      ? const AdaptiveProgressIndicator(
                          size: 18,
                          strokeWidth: 2,
                        )
                      : const Text('Show my recovery code'),
                ),
              ),
              const SizedBox(height: AppSpacing.xs),
              SizedBox(
                width: double.infinity,
                child: TextButton(
                  // Dismissible on purpose. This is an upgrade offer to people
                  // whose accounts work today; blocking the app on it would
                  // make a safety improvement read as a hostage situation.
                  onPressed: _busy
                      ? null
                      : () => Navigator.of(context).pop(false),
                  child: const Text('Not now'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
